name: Real-Time-MNIST
channels:
  - defaults
dependencies:
  - h5py=2.8.0
  - keras=2.3.1
  - matplotlib=3.5.1
  - numpy=1.21.5
  - opencv=3.4.2
  - pillow=9.0.1
  - pip=21.2.4
  - python=3.7.13
  - scikit-learn=1.0.2
  - tensorflow=2.1.0
